### ISSUE TITLE
RangeError: Max payload size exceeded

### ISSUE THREAD

**Issue by cxplay** [CodyTseng/nostr-relay-tray#8]
ref to: https://github.com/websockets/ws/issues/1543

```text
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
RangeError: Max payload size exceeded
    at Receiver.haveLength (C:\Users\CXPLAY\AppData\Local\nostr_relay_tray\app-1.2.3\resources\app.asar\node_modules\ws\lib\receiver.js:423:28)
    at Receiver.getPayloadLength16 (C:\Users\CXPLAY\AppData\Local\nostr_relay_tray\app-1.2.3\resources\app.asar\node_modules\ws\lib\receiver.js:374:10)
    at Receiver.startLoop (C:\Users\CXPLAY\AppData\Local\nostr_relay_tray\app-1.2.3\resources\app.asar\node_modules\ws\lib\receiver.js:162:16)
    at Receiver._write (C:\Users\CXPLAY\AppData\Local\nostr_relay_tray\app-1.2.3\resources\app.asar\node_modules\ws\lib\receiver.js:98:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.socketOnData (C:\Users\CXPLAY\AppData\Local\nostr_relay_tray\app-1.2.3\resources\app.asar\node_modules\ws\lib\websocket.js:1303:35)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
```

**Comment by CodyTseng** [comment]
This is because I have restricted the payload maximum to 128k. You might be trying to insert a huge event.

**Comment by cxplay** [comment]
> This is because I have restricted the payload maximum to 128k. You might be trying to insert a huge event.

You're right, but I have absolutely no idea which event is causing this. Is there any option to stop the warning window from popping up?

**Comment by CodyTseng** [comment]
> You're right, but I have absolutely no idea which event is causing this. Is there any option to stop the warning window from popping up?

You can clone the source code, delete line 143 in main.js, and then package and run it.

**Comment by CodyTseng** [comment]
In the future, I will add a settings panel to allow for setting some restrictions.
